# fly.toml app configuration file generated for ensta-cloud-computing on 2023-11-09T09:28:11+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ensta-cloud-computing"
primary_region = "cdg"

[build]
  dockerfile = ".docker/multistage.Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
